# main workflow

on:
  push:
    branches: [master]
  # allow manual trigger
  workflow_dispatch:
  
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute simple command
      run: echo "Hello world"
  
