# main workflow

on:
  push:
    branches: [master]
  # allow manual trigger
  workflow_dispatch:
  
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute simple command
      run: echo "Hello world"
      
      
    - name: Execute multiple commands
      run: |
        npm -v
        node -v


    - name: Python Command in a Python Shell
      run : |
        import platform
        print(platform.processor())
      shell: python  

  run-windows-command-job:
    runs-on: windows-latest
    steps:
    - name: Directory Powershell
      run: Get_Location
    - name: Run a Command on bash on Windows
      shell: bash
      run: pwd
      
      run: |
        

        
        
  
